/**
 * Action Messages Interfaces
 *
 * Core data structures for the Action Messages engine.
 * Used by ActionMessagesService to compare newly planned orders against
 * existing FIRME/LIBERADA orders and generate action messages indicating
 * what changes are needed (CANCEL, INCREASE, REDUCE, EXPEDITE, NEW).
 *
 * @see Story 3.8 — Action Messages
 * @see FR-039 — Action Messages
 */

/**
 * Types of action messages generated by comparing planned vs existing orders.
 *
 * - CANCEL: Existing order has no corresponding planned requirement
 * - INCREASE: Existing order quantity is less than planned requirement
 * - REDUCE: Existing order quantity exceeds planned requirement (but not zero)
 * - EXPEDITE: Existing order delivery date is later than planned need date
 * - NEW: Planned requirement with no corresponding existing order
 */
export enum ActionMessageType {
  CANCEL = 'CANCEL',
  INCREASE = 'INCREASE',
  REDUCE = 'REDUCE',
  EXPEDITE = 'EXPEDITE',
  NEW = 'NEW',
}

/**
 * A single action message describing a required change to an order.
 */
export interface ActionMessage {
  /** The type of action required */
  readonly type: ActionMessageType;

  /** The product identifier */
  readonly produtoId: string;

  /** The existing order ID (null for NEW messages) */
  readonly existingOrderId: string | null;

  /** The planned order ID (null for CANCEL messages) */
  readonly plannedOrderId: string | null;

  /** Concise human-readable message (<= 100 chars for VarChar(100)) */
  readonly message: string;

  /** Quantity delta for INCREASE/REDUCE messages (null for others) */
  readonly deltaQuantity: number | null;

  /** Number of days to expedite for EXPEDITE messages (null for others) */
  readonly deltaDays: number | null;

  /** Existing order delivery date (null when not applicable) */
  readonly currentDate: Date | null;

  /** Planned order need date (null when not applicable) */
  readonly requiredDate: Date | null;
}

/**
 * Input for the action messages generation process.
 */
export interface ActionMessagesInput {
  /** The planning execution identifier */
  readonly execucaoId: string;

  /** Newly planned orders to compare against existing orders */
  readonly plannedOrders: readonly PlannedOrderRef[];
}

/**
 * Reference to a planned order used for comparison.
 */
export interface PlannedOrderRef {
  /** The planned order record ID */
  readonly id: string;

  /** The product identifier */
  readonly produtoId: string;

  /** Order type: COMPRA (purchase) or PRODUCAO (production) */
  readonly tipo: 'COMPRA' | 'PRODUCAO';

  /** Planned order quantity */
  readonly quantidade: number;

  /** Date when the material is needed */
  readonly dataNecessidade: Date;
}

/**
 * Output of the action messages generation process.
 * Contains all generated messages and summary counts by type.
 */
export interface ActionMessagesOutput {
  /** The planning execution identifier */
  readonly execucaoId: string;

  /** All generated action messages */
  readonly messages: readonly ActionMessage[];

  /** Count of CANCEL messages */
  readonly totalCancel: number;

  /** Count of INCREASE messages */
  readonly totalIncrease: number;

  /** Count of REDUCE messages */
  readonly totalReduce: number;

  /** Count of EXPEDITE messages */
  readonly totalExpedite: number;

  /** Count of NEW messages */
  readonly totalNew: number;
}
