/**
 * BOM Explosion Interfaces
 *
 * Core data structures for the Multi-Level BOM Explosion Engine.
 * Used by BomExplosionService (pure calculation) to compute low-level codes
 * and cascade gross requirements from finished products down through the
 * entire bill of materials hierarchy.
 *
 * @see Story 3.4 — Multi-Level BOM Explosion
 * @see FR-036 — BOM Explosion
 */

/**
 * A single time-phased demand entry.
 * Represents a quantity required within a specific planning period.
 */
export interface TimePhasedDemand {
  /** Start date of the planning period (inclusive) */
  readonly periodStart: Date;

  /** End date of the planning period (inclusive) */
  readonly periodEnd: Date;

  /** Demand quantity for this period */
  readonly quantity: number;
}

/**
 * A BOM line for explosion (pre-fetched from DB).
 * Represents one parent-child relationship in the bill of materials.
 */
export interface BomLineInput {
  /** The parent product ID */
  readonly produtoPaiId: string;

  /** The child (component) product ID */
  readonly produtoFilhoId: string;

  /** Quantity of child required per unit of parent */
  readonly quantidade: number;

  /** Loss/scrap percentage — applied as (1 + perdaPercentual / 100) multiplier */
  readonly perdaPercentual: number;
}

/**
 * Input for the BOM explosion engine.
 * All data is pre-fetched by the caller — this is a pure calculation interface.
 */
export interface BomExplosionInput {
  /** MPS demand for finished products (level 0) — produtoId -> time-phased demands */
  readonly mpsRequirements: ReadonlyMap<string, readonly TimePhasedDemand[]>;

  /** Active BOM lines (pre-filtered: ativo=true, within validity dates) */
  readonly bomLines: readonly BomLineInput[];

  /** Product types for level-0 identification — produtoId -> TipoProduto */
  readonly productTypes: ReadonlyMap<string, string>;
}

/**
 * Low-level code assignment map.
 * Maps each product ID to its assigned low-level code (depth in the BOM hierarchy).
 * Level 0 = finished products (ACABADO); higher numbers = deeper in hierarchy.
 * If an item appears at multiple levels, it receives the HIGHEST level number.
 */
export interface LowLevelCodeMap {
  readonly [produtoId: string]: number;
}

/**
 * Result of BOM explosion.
 * Contains low-level codes for all items and the cascaded gross requirements
 * ready for netting by NetRequirementService.
 */
export interface BomExplosionResult {
  /** Low-level code for each product in the BOM */
  readonly lowLevelCodes: LowLevelCodeMap;

  /** Gross requirements generated by explosion — produtoId -> time-phased demands */
  readonly grossRequirements: ReadonlyMap<string, readonly TimePhasedDemand[]>;
}
